### ISSUE TITLE
Crash when empty list is used in prepared statement

### ISSUE THREAD

**Issue by dysphie** [duckdb/duckdb-node-neo#128]
The library crashes without any errors when empty lists are used in a prepared statement

```js

await conn.run(`
  CREATE TABLE IF NOT EXISTS performances (
    id INTEGER PRIMARY KEY DEFAULT nextval('performance_id'),
    mutators VARCHAR[],
    tags VARCHAR[]
  );
`);

await conn.run(`
    INSERT INTO performances (mutators, tags)
    VALUES ($mutators, $tags)`, {
    mutators: listValue([]), // <--
    tags: listValue([])
});

console.log('never prints')
```

**Comment by jraymakers** [comment]
Thanks for the report! This is indeed a bug. I have an idea where it might be. Here's an even simpler repro:

```
const prepared = await connection.prepare('select ?');
prepared.bindList(1, listValue([]), LIST(INTEGER));
```

**Comment by jraymakers** [comment]
Merged a [fix](https://github.com/duckdb/duckdb-node-neo/pull/129). I'll get a release out soon.

**Comment by jraymakers** [comment]
Fixed in 1.1.3-alpha.11.

**Comment by dysphie** [comment]
Thank you! Although it appears to still crash in some scenarios:

```js
await conn.run('select $a', { 'a': listValue([]) })
```
This doesn't happen when types are specified:
```js
await conn.run('select $a', { 'a': listValue([]) }, { 'a': LIST(VARCHAR) })
```

**Comment by jraymakers** [comment]
Sure enough. I'll investigate that additional case.

**Comment by jraymakers** [comment]
Merged a [fix](https://github.com/duckdb/duckdb-node-neo/pull/132). It'll go out with the next release; I'll do that soon, but there one more issue I want to investigate first.

**Comment by jraymakers** [comment]
Published 1.1.3-alpha.12 with the second fix.
